name: Update Blog Archive

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  update_blog_archive:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build and Run Blog Crawler
        run: |
          go build -o blog_crawler
          ./blog_crawler

      - name: Auto Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update xargin_blogs.md"
          branch: master
          push_options: --force
